server:
  port: 8181

spring:
  application:
    name: ByblosBankAMS

byblosbank-ams:
  webclient:
    connect-timeout-ms: 10000
    read-timeout-ms: 10000
    write-timeout-ms: 10000
    max-in-memory-size: 10485760 # 10MB
    content-type: 'application/json'
    accept-type: 'application/json'
    creatio-base-url: 'placeholder'

# -------- keycloak -----------------
keycloak:
  realm: byblos
  bearer-only: true
  auth-server-url: https://testauthz.byblosbank.com.lb/auth
  ssl-required: external
  resource: AMS-MW
  use-resource-role-mappings: true
  principal-attribute: preferred_username